version: "3.7"

services:
  rentx_database:
    image: postgres
    container_name: rentx_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  rentx_node:
    build: .
    container_name: rentx_node
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app/rentx
    links:
      - rentx_database
    depends_on:
      - rentx_database

volumes:
  pgdata:
    driver: local